#!/bin/bash

# Prompt the user to enter a number
echo "Enter a number:"
read num

# Initialize a counter
counter=1

# Use a while loop to print numbers from 1 to the given number
echo "Numbers from 1 to $num:"
while true; do
    echo $counter
    ((counter++))
    
    # Check if the counter exceeds the given number
    if [ $counter -gt $num ]; then
        break
    fi
done

