#!/bin/bash

# Prompt the user to enter a number
echo "Enter a number:"
read num

# Initialize a counter
counter=1

# Use a while loop to print numbers from 1 to the given number
echo "Numbers from 1 to $num:"
while [ $counter -le $num ]; do
    echo $counter
    ((counter++))
done
